### PR TITLE
Support for both 'valueQuantity' and 'valueString'  for the patient g…

### PR DESCRIPTION
**Pull request by vlad-ignatov**
…estationalAge...

### CODE REVIEW

**Comment by dpopcmh** [comment]
i dont know if this is something you want in the main branch, but the Cerner FHIR service returns 0 in teh value quantity, at the same time it returns 25W 4D in teh value string. The presence of this 0 causes vlads code to never look at the string value, instead using the 0.

**Comment by dpopcmh** [comment]
it uses the 40, I meant.  In my local code base, I just swapped the order of values read to look at teh value string before the value quanitity and it now works for me.

**Comment by jmandel** [comment]
Thanks for the warning -- if you could include an example here we could
reference it from the code, to close the documentation loop. There's no
point in our doing parsing both ways unless it actually works for your use
case :-)

  -J

**Comment by dpopcmh** [comment]
here is the JSON Cerner provides us:
     "valueQuantity": {
                    "value": 0,
                    "units": "",
                    "code": ""
                },
                "valueString": {
                    "value": "32W 4D",
                    "units": "",
                    "code": ""
                },

try to run this new code from Vlad against this data, and see if it behaves as you would expect.

**Comment by vlad-ignatov** [comment]
OK then. I just made 'patch-2'

**Comment by jmandel** [comment]
Great, merged `patch-2` -- thanks! (In general, it's good if you can submit
a PR for tracking purposes, but it's not strictly necessary.)

**Pull request merged**
