### PR TITLE
IHC customizations

### PR DESCRIPTION
**Pull request by dpopcmh**
read chart and menu data from a local file.
hide parent view
add new olsen chart type

### CODE REVIEW

**Comment by jmandel** [comment]
Thanks for sharing these changes, @dpopcmh !

We'd love to incorporate many of changes back into the app. Below, I'll outline a few tweaks that we'd love if you could address with an additional commit on this Pull Request. The general idea is to avoid hardcoding implementation-specific decisions; instead, these should be configurable. This will be a big help for long-term maintenance. 

 * Thanks for the additional Olsen data, and for extracting out the list of reference tables into a separate .JSON file!

 * I like the direction of moving configuration data (menu items, reference tables) out of code and into external config files. But rather than dynamically loading these at runtime via Ajax requests, it might make sense to have a static build process that outputs a ready-to-go web app. This would help with performance, and would also address what appears to be a race condition introduced at https://github.com/dpopcmh/growth-chart-app/blob/ae7aa460302bbecf9003e3b07d98e702b54bbd47/js/gc-charts-data.js#L21 (where a global variable is mutated in an Ajax callback, with no guarantee that the relevant processing logic hasn't already run before the callback completes).

 * Avoid calling `window.alert` in error conditions, to fit with the style of the app. If the message is a debugging message for developers, use `console.log`; if it's a user-facing message, try displaying an in-app message or dialog. 

 * Rather than commenting out the parental view in a hard-coded fashion, it would be helpful to expose a configuration-time option defining whether the view should be shown or hidden. This configuration setting could be applied during a static build process (see my comment above) or even at runtime.

 * IHC-specific configuration data (e.g. changing version to "IHC") would be best stored on an IHC branch. Or better yet, populate these fields in a static build process (again, see above) so we can get by with just one code branch.

**Comment by nschwertner** [comment]
+ @vlad-ignatov who developed the app

Thank you for contributing, @dpopcmh Josh's comments are right on target.

**Comment by dpopcmh** [comment]
These are the single best comments I have ever received about a code check in! :)
I plan to work on a few of these changes when I return from vacation.I think a couple of them I will leave as they stand, and if you pull my code into the main branch, you can just leave out that file, such as the about box.I know subversion allows for that, so I hope Git does as well.
I will be in touch when this is done.Chad Hodge
Date: Mon, 29 Jun 2015 14:59:52 -0700

**Comment by dpopcmh** [comment]
@jmandel I made a few commits today that I hope address most of your concerns.  Please give this fork another look and let me know what you think.

**Comment by nschwertner** [comment]
Josh, shall I give management privileges to this repo to Vlad so that he can be involved in the code maintenance?

**Comment by jmandel** [comment]
Yes please @nschwertner .

**Comment by dpopcmh** [comment]
any thoughts on pulling these changes into main? what other changes would you like me to make?

**Comment by jmandel** [comment]
Thanks for the remidner @dpopcmh, and for these changes, which are great. From my initial comments, the main remaining concern is about the potential race condition that I pointed out. Do you agree with my assessment here?

Would also love to know if @vlad-ignatov has any comments!

**Comment by dpopcmh** [comment]
I do agree with you @jmandel, I just don't know what to do to solve that issue.  If you have any suggestions, I would be happy to modify the code accordingly. thanks!

**Comment by dpopcmh** [comment]
BTW, there is newer Fenton curve data available.  We are in the process of licensing it right now.  I don't think our license will allow me to commit that newer data here, but you may want to look into it.

**Comment by jmandel** [comment]
The codebase is written with the assumption that the data are available at load time, so the simplest fix would be to move the data into an external file like `gc-charts-data-only.js` with content:

```
var GC;
if (!GC) {
    GC = {};
}
GC.DATA_SETS = {
  .... all reference data here
}
```

And then ensure this file is loaded in a `script` tag *before* `gc-charts-data.js`.

To make this more maintainable, I would recommend adding a new directory to the project like `growth-curve-data`, and define a common convention for representing the source data (e.g. as a set of CSV files, or JSON files, or whatever).  Then write a simple shell script or python script like `process-reference.data.py` that can process the directory automatically, and re-generate  `gc-charts-data-only.js`. Then all edits would be made to the CSV files (or whatever), and it would always be safe to run
`process-reference-data`.

This is the gist of what I mean by a "static build process".

Does this make sense?

**Comment by vlad-ignatov** [comment]
I think Josh explained it very well. Loading the data via async. request can lead to unpredictable behaviour. Converting that to  `.js` file and loading it with `<script>` tag before `gc-charts-data.js` is the simplest way to fix that. 

It is also possible to create a task and add it to the initialization queue. Each task in that queue has label that is shown on the initial loading screen. I can explain how this can be done if you are interested.

**Comment by dpopcmh** [comment]
thanks for the feedback. I like the idea of adding this as a init task in the queue.  I will look at the code to try and figure it out, but if you want to explain it, that would be great.This is a really great app, by the way.  I am very impressed.Chad Hodge

Date: Wed, 29 Jul 2015 09:18:41 -0700

**Comment by vlad-ignatov** [comment]
Thank you. You can try it. I nave forgotten the code details so excuse me if I miss something, but here is what I would do:

First get the self-executing function starting at https://github.com/dpopcmh/growth-chart-app/blob/master/js/gc-charts-data.js#L34 and move it inside the success handler after the catch statement like so:

```js
$.ajax({
        url: "GCCurveDataJSON.txt",
        success: function (data) {
            try {
                GC.DATA_SETS = JSON.parse(data);
            }
            catch (exc) {
                alert("error reading curve data from JSON file." +" \n" + exc);
            }
            // PUT THE SORTING CODE HERE
        },
        ...
```
This code is currently useless since it gets executed before the AJAX callbacks.

Then put the entire thing in function:
```js
function loadDataSets(done) {
    $.ajax({
        url: "GCCurveDataJSON.txt",
        ...
    });
}
```

You should call the `done` callback at the end of the success handler and simply do not call it in case of error (this way the task queue will stop and the app will not load in case of error).

Then move this function to `/js/gc-app.js` (inside the closure)

Finally add it to the initialization queue. For example on line 1391 you can add something like this:
```js
QUEUE.add("Loading DataSets...", loadDataSets);
```

You can add translation for the task message or just reuse `NS.str("STR_LoadingData")`.

Finally, I would use ``console.error`` instead of `alert` and add `return` at the end of the `catch` block.

Hope this helps.

**Comment by dpopcmh** [comment]
@nschwertner, @jmandel.  I believe this commit solves the remaining issues.  Let me know what you think.  I would like to get this code into the main branch. let me know what else I can do to make that happen.

**Comment by jmandel** [comment]
@dpopcmh Excellent -- a few more loose ends to tie up and we'll be set to merge.

**Comment by dpopcmh** [comment]
@jmandel regarding the gestage valuestring vs valuequantity.
We too would much prefer a valuequantity. Unfortunately, the Cerner FHIR service that we are using is returning it as a valuestring in the format "32W 4D".  We have discussed this concern with them, but they are unwilling to provide the valuequantity as we asked for.  I can remove this code from the main branch if you prefer, but users of Cerner will face this situation.  please advise.

**Comment by dpopcmh** [comment]
@jmandel My latest commit should address your comments. give it a look

**Comment by jmandel** [comment]
Merged -- thanks @dpopcmh! @nschwertner please let me know if any cleanup is required.

**Comment by nschwertner** [comment]
Vlad (@vlad-ignatov), can you take a look?

**Comment by jmandel** [comment]
One thing I think we do want to clean up is the `valueQuantity` issue mentioned above. We should obviously support quantities for the age value. Optionally we might want to consider detecting the degraded condition when a string is supplied, and fall back to that with heuristic parsing (but this way lies madness, if we can't get broad agreement that an age ia a number and not a string).

**Comment by dpopcmh** [comment]
@jmandel is there anything you still need from me? it looks like Vlads code might have addressed the issue you raised with the days of week being used as a tenth of a week? just let me know what else I can do to help. thanks!

**Comment by jmandel** [comment]
I think we're in good shape -- we'll update to fix. But I wanted to keep
you in the loop and warn you that your code may not behave the way you
expect it to (days are 1/7 weeks vs. 1/10 weeks).

  -J

**Comment by jmandel** [comment]
Thanks for the fix-up in https://github.com/smart-on-fhir/growth-chart-app/pull/2, @vlad-ignatov !

**Pull request merged**
